### PR TITLE
Update compound annotations to link to PubChem URL

### PR DESCRIPTION
**Pull request by sbesson**
See also https://github.com/IDR/idr0081-georgi-adenovirus/pull/1

### CODE REVIEW

**Comment by sbesson** [comment]
This has now been deployed to `pilot-idr0088` and is ready for review.

**Comment by sbesson** [comment]
Currently, IDR compounds are normalized based on compound names. In tersm of storage, this means a single canonical map annotation with namespace `openmicroscopy.org/mapr/compound` is maintained for each value of the mandatory `Compound Name` key. This map annotation is linked to all images/wells annotated with this compound. Other keys may exist and in the large majority of cases, a `Compound Name URL` key has been created pointing to a NCBI search historically and the PubChem URL more recently. 

Unfortunately, the reality of the compound ecosystem is much more challenging and forces us to review this representation. We already have the case of separate annotation in the database using different compound name synonyms (e.g. DMSO vs Dimethyl Sulfoxide) to refer to the same entity. A recent submission now brings the opposite case where two submissions are using stereoisomers where the submitted compound common name is identical but these compounds have separate SMILES, InChi keys, PubChem IDs.

To solve this problem, 1461030 proposes to change the way  compound annotations are normalize and  use the combination of `Compound Name` and `Compound Name URL` instead. This is effectively the same approach as the one used for genes which use the combination of Gene Name + Gene Identifier.

This prototype has been tested on `pilot-idr0100`. With the current infrastructure, the new set of canonical keys enforces that every compound annotation MUST have both keys present however setting the URL value to empty is sufficient to satisfy the condition and the key does not show up in the UI. The ~200 compounds in the database were reviewed and updated as follows:

```
omero obj map-set MapAnnotationI:7393241 mapValue "Compound Name URL" https://www.ebi.ac.uk/chembldb/target/inspect/CHEMBL3810
omero hql -q --limit -1 --style csv --ids-only "select m from MapAnnotation m join m.mapValue mv where m.ns='openmicroscopy.org/mapr/compound' and size(mv) <2" > ids.tx
for i in $(cat ids.tx | cut -d ',' -f 2); do omero obj map-set $i mapValue "Compound Name URL" ""; done
```

After updating the database, the compound from `idr0092` was repopulated using the changes PR as follows:

```
omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0092-ostrop-organoid/screenA/idr0092-screenA-bulkmap-config.yml Screen:2451
omero metadata populate --context bulkmap --wait 300 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"]}' --cfg idr0092-ostrop-organoid/screenA/idr0092-screenA-bulkmap-config.yml Screen:2451
```

As a result, new compound annotations associated with the PubChem URL are created for `idr0092` e.g. DMSO:

Screenshot 2020-11-15 at 21 14 37

while previous DMSO annotation are unchanged e.g. for `idr0030`:

Screenshot 2020-11-15 at 21 15 37

A compound search for DMSO will still returns all images associated with both separate annotations i.e. the integration by compound name is still functional:

Screenshot 2020-11-15 at 21 16 05

Overall, this approach has the advantage of unblocking the upcoming release and should be a good compromise between annotating studies using chemical variations of compounds with identical names and preserving the integration by compound names.

A few comments and potential limitations of this approach:

- existing compound annotations for historical studies will not automatically be updated if the same compound is provided with a different URL in a new submission and will need individual re-annotation instead.
- the bulk2map configuration file of every new compound study will need to include both compound keys else the population will fail during the loading of the compound annotations post `prod90`
- for future submissions containing compounds provided without any associated PubChem CID,  an empty `Compound Name URL` value will need to be created
-  `Compound Name`/`Compound Name URL` feels a bit less well-defined than `Gene Name`/`Gene Identifier` to act as primary keys. The choices made in this proposal were largely driven by feasibility reasons given the size of the IDR compound database (35K compounds). If we start exporting images with compound metadata as JSON-LD, we might have a good opportunity to rethink how best to describe compounds using our experience of the last years.

**Comment by joshmoore** [comment]
(the third screenshot appears broken)

**Comment by joshmoore** [comment]
> * for future submissions containing compounds provided without any associated PubChem CID,  an empty `Compound Name URL` value will need to be created

Thinking forward, I wonder if the `@id` for these will need to be something like idr.openmicroscopy.org/locally-defined/compound/$NAME`.

**Comment by sbesson** [comment]
Merging for deployment on `prod90`

**Comment by sbesson** [comment]
Now deployed on `prod90`

**Pull request merged**
